// ALPINEA — multilingual content
window.ALPINEA_DATA = {
  cat: {
    nav: {
      about: "Estudi",
      services: "Serveis",
      packs: "Packs",
      venues: "Espais",
      team: "Equip",
      journal: "Diari",
      contact: "Contacte",
      cta: "Sol·licitar proposta",
    },
    hero: {
      eyebrow: "Agència MICE & Comunicació · Cerdanya",
      title: ["Esdeveniments", "d'altura,", "fets a mida", "del Pirineu."],
      titleClean: "Esdeveniments d'altura, fets a mida del Pirineu.",
      lead:
        "Dissenyem trobades corporatives, congressos, incentius i campanyes de comunicació que aprofiten l'energia, el paisatge i l'artesania de la Cerdanya. Cada projecte, una experiència irrepetible a 1.200 metres.",
      ctaPrimary: "Comencem un projecte",
      ctaSecondary: "Veure carta de serveis",
      stat1: ["8", "persones a l'estudi"],
      stat2: ["38", "espais singulars seleccionats"],
      stat3: ["1.200 m", "altitud mitjana de la vall"],
    },
    about: {
      eyebrow: "Estudi",
      title: "Una agència arrelada al territori, pensada per a marques exigents.",
      body: [
        "Alpinea neix aquest 2026 a Puigcerdà com la primera agència especialitzada de la Cerdanya en MICE, esdeveniments corporatius i comunicació estratègica. Combinem la mirada editorial d'un estudi creatiu amb el rigor operatiu d'una DMC.",
        "Volem treballar amb empreses, institucions i marques que busquen un escenari diferent: un entorn natural d'alta muntanya, una xarxa de proveïdors locals de confiança i un equip que coneix cada vall, cada masia i cada cuiner del territori.",
      ],
      pillars: [
        ["01", "Coneixement del territori", "Hem caminat, dormit i cuinat a tots els espais que oferim."],
        ["02", "Producció amb rigor", "Pressupostos transparents, calendari realista, execució impecable."],
        ["03", "Mirada editorial", "Cada esdeveniment es comunica abans, durant i després com una història."],
        ["04", "Petjada local", "Treballem amb productors, artesans i guies de la vall."],
      ],
    },
    services: {
      eyebrow: "Carta de serveis",
      title: "Tot el que necessites per produir, comunicar i fer memorable un projecte.",
      lead:
        "Oferim cobertura 360°: des de la primera idea i la cerca d'espai fins a la cobertura de premsa i el material audiovisual final.",
      categories: [
        {
          tag: "01 — MICE",
          name: "Esdeveniments corporatius",
          desc:
            "Convencions, kick-offs, juntes i jornades estratègiques amb producció integral i acompanyament executiu.",
          items: [
            "Convencions i kick-offs",
            "Juntes i consells",
            "Llançaments de producte",
            "Activacions de marca",
          ],
        },
        {
          tag: "02 — Incentius",
          name: "Incentius i team building",
          desc:
            "Programes de 2 a 5 dies amb activitats outdoor, gastronomia d'autor i allotjaments singulars dissenyats al detall.",
          items: [
            "Esquí, raquetes i muixing",
            "Rutes BTT i trekking",
            "Tallers gastronòmics",
            "Wellness i muntanya",
          ],
        },
        {
          tag: "03 — Congressos",
          name: "Congressos i convencions",
          desc:
            "Secretaria tècnica, gestió d'inscripcions, ponents i streaming per a esdeveniments de fins a 600 assistents.",
          items: [
            "Secretaria tècnica",
            "Gestió de ponents",
            "Streaming i híbrids",
            "Apps i acreditacions",
          ],
        },
        {
          tag: "04 — DMC",
          name: "Destination Management",
          desc:
            "Som el teu partner local: transfers, allotjaments, restauració, guies i logística d'última milla.",
          items: [
            "Cerca i contractació d'espais",
            "Transfers i mobilitat",
            "Hospitality desks",
            "Acompanyament 24/7",
          ],
        },
        {
          tag: "05 — Comunicació",
          name: "Comunicació & RRPP",
          desc:
            "Estratègia, relat i relació amb mitjans abans, durant i després de l'esdeveniment per amplificar-ne l'impacte.",
          items: [
            "Estratègia i missatges clau",
            "Notes i rodes de premsa",
            "Influencer & creator relations",
            "Cobertura editorial",
          ],
        },
        {
          tag: "06 — Producció",
          name: "Producció audiovisual",
          desc:
            "Vídeo, fotografia i direcció d'art en localitzacions úniques de la Cerdanya, amb equips locals.",
          items: [
            "Vídeo corporatiu i aftermovie",
            "Fotografia editorial",
            "Direcció d'art",
            "Streaming multicàmera",
          ],
        },
        {
          tag: "07 — Branding",
          name: "Identitat & disseny",
          desc:
            "Identitat visual de l'esdeveniment, sistema gràfic, senyalètica i materials impresos amb cura artesanal.",
          items: [
            "Naming i clau visual",
            "Senyalètica i wayfinding",
            "Convidats i merchandising",
            "Webs i landings",
          ],
        },
        {
          tag: "08 — Bodes",
          name: "Bodes & celebracions privades",
          desc:
            "Un nombre limitat de celebracions privades l'any, amb la mateixa exigència editorial que els nostres projectes corporatius.",
          items: [
            "Direcció creativa",
            "Producció integral",
            "Coordinació de proveïdors",
            "Wedding concierge",
          ],
        },
      ],
    },
    packs: {
      eyebrow: "Packs",
      title: "Productes tancats, llestos per reservar.",
      lead:
        "Quatre programes ja dissenyats que combinen allotjament, espai, restauració i activitats. Punt de partida; els personalitzem amb tu en una trucada.",
      note: "Preus orientatius per persona, IVA no inclòs. Mínim 20 pax. Disponibilitat segons temporada.",
      ctaPack: "Vull aquest pack",
      ctaCustom: "Vull-ne un de mida",
      labels: { duration: "Durada", group: "Grup", season: "Temporada", from: "Des de", includes: "Què inclou" },
      list: [
        {
          code: "P01", slug: "cims-estrategia",
          name: "Cims & Estratègia",
          tag: "Off-site executiu",
          tagline: "Dos dies per pensar lluny, decidir a prop.",
          duration: "2 dies / 1 nit",
          group: "8–20 pax",
          season: "Tot l'any",
          price: "1.180 €",
          tone: "alpine",
          includes: [
            ["Allotjament", "Mas de la Coma · habitació boutique"],
            ["Espai", "Sala de juntes amb vistes + breakout al bosc"],
            ["Restauració", "Esmorzar, dinar de treball, sopar de tast (5 temps)"],
            ["Activitats", "Trekking guiat a la Tossa Plana + sessió de wellness"],
            ["Extra", "Facilitador estratègic + acta visual de la jornada"],
          ],
        },
        {
          code: "P02", slug: "kick-off-cerdanya",
          name: "Kick-off Cerdanya",
          tag: "Convenció anual",
          tagline: "Tot l'equip, un cap de setmana, una vall.",
          duration: "3 dies / 2 nits",
          group: "80–300 pax",
          season: "Set–Jun",
          price: "780 €",
          tone: "crowd",
          includes: [
            ["Allotjament", "Hotel del Llac ★★★★ · pensió completa"],
            ["Espai", "Sala plenària + 4 breakouts + plaça per a gala"],
            ["Restauració", "Coffee artesà, dinar buffet, sopar de gala signat"],
            ["Activitats", "Team building \"Travessa de la Cerdanya\" + tast de formatges"],
            ["Extra", "Producció audiovisual (aftermovie 90'') + senyalètica"],
          ],
        },
        {
          code: "P03", slug: "snow-incentive",
          name: "Snow Incentive",
          tag: "Incentiu hivern",
          tagline: "Esquí al matí, gala a la nit.",
          duration: "3 dies / 2 nits",
          group: "30–120 pax",
          season: "Des–Mar",
          price: "1.450 €",
          tone: "ice",
          includes: [
            ["Allotjament", "Hotel boutique al peu de pistes"],
            ["Espai", "Restaurant d'altura privatitzat + sala de juntes"],
            ["Restauració", "Esmorzar muntanya, dinar a pistes, sopar maridat"],
            ["Activitats", "Esquí amb monitor, raquetes, mushing o spa"],
            ["Extra", "Forfaits, transfers i material inclosos"],
          ],
        },
        {
          code: "P04", slug: "estiu-editorial",
          name: "Estiu Editorial",
          tag: "Press trip & activació",
          tagline: "Tres dies per a periodistes, creators i clients top.",
          duration: "3 dies / 2 nits",
          group: "12–40 pax",
          season: "Jun–Set",
          price: "1.290 €",
          tone: "forest",
          includes: [
            ["Allotjament", "Masia Cal Marrufès · habitacions singulars"],
            ["Espai", "Pati exterior, era i celler privatitzats"],
            ["Restauració", "Tres àpats km0 amb xef convidat"],
            ["Activitats", "Ruta gastronòmica + taller artesà + bany al riu"],
            ["Extra", "Fotògraf editorial + kit de premsa personalitzat"],
          ],
        },
      ],
    },
    venues: {
      eyebrow: "Espais",
      title: "Una xarxa de 38 venues seleccionats a la vall.",
      lead:
        "Treballem amb allotjaments, restaurants, espais singulars i empreses de serveis arreu de la Cerdanya. Aquí és la nostra selecció completa de partners de qualitat.",
      list: [
        {
          name: "Hotel Bernat de So",
          place: "Llívia",
          capacity: "21 habitacions, fins a 31 pax",
          tags: ["Hotel ★★★", "Sala reunions", "Sostenible"],
          tone: "stone",
        },
        {
          name: "Hotel del Lago",
          place: "Puigcerdà",
          capacity: "21 habitacions, fins a 41 pax",
          tags: ["Hotel ★★★★", "Spa", "Piscina climatitzada"],
          tone: "lake",
        },
        {
          name: "Cerdanya Viva",
          place: "Prullans",
          capacity: "102 habitacions, fins a 437 pax",
          tags: ["Ecohotel", "Sala gran format", "Turisme regeneratiu"],
          tone: "forest",
        },
        {
          name: "Alp Hotel Masella",
          place: "Alp (Masella)",
          capacity: "146 habitacions, fins a 600 pax",
          tags: ["Hotel ★★★", "Peu de pistes", "Piscina interior/exterior"],
          tone: "ice",
        },
        {
          name: "Hotel Torre del Remei",
          place: "Bolvir",
          capacity: "24 habitacions, fins a 55 pax",
          tags: ["Palauet modernista", "Jardins de 3 ha", "Gastronomia de qualitat"],
          tone: "wine",
        },
        {
          name: "Hotel del Prado",
          place: "Puigcerdà",
          capacity: "56 habitacions, fins a 110 pax",
          tags: ["Hotel gastronòmic", "Jardí i piscina", "Producte km0"],
          tone: "wine",
        },
        {
          name: "Hotel Fontanals Golf",
          place: "Fontanals de Cerdanya",
          capacity: "60 habitacions, fins a 180 pax",
          tags: ["Golf", "Esquí", "Senderisme"],
          tone: "forest",
        },
        {
          name: "Hotel&Spa La Collada",
          place: "Toses",
          capacity: "90 habitacions, fins a 270 pax",
          tags: ["Spa", "Piscina climatitzada", "Sales reunions"],
          tone: "alpine",
        },
        {
          name: "Hotel Villa Paulita",
          place: "Puigcerdà",
          capacity: "35 habitacions, fins a 80 pax",
          tags: ["Noucentista", "Vistes al llac", "Grups MICE"],
          tone: "stone",
        },
        {
          name: "Hotel Solineu",
          place: "Alp (la Molina)",
          capacity: "53 hab + 35 apart, fins a 137 pax",
          tags: ["Ambient familiar", "Tot l'any", "Sales reunions"],
          tone: "ice",
        },
        {
          name: "Hotel-Restaurant Ca l'Eudald",
          place: "Alp",
          capacity: "25 habitacions, fins a 62 pax",
          tags: ["Cuina pirinenca", "Terrassa amb jardí", "Grups"],
          tone: "forest",
        },
        {
          name: "Cal Rei",
          place: "Lles de Cerdanya",
          capacity: "Fins a 25 pax",
          tags: ["Allotjament rural", "Restaurant", "Vistes al Cadí-Moixeró"],
          tone: "alpine",
        },
        {
          name: "Les Feixes Llargues",
          place: "Bolvir",
          capacity: "Fins a 19 pax",
          tags: ["Allotjament rural", "Sala reunions", "Sostenible"],
          tone: "forest",
        },
        {
          name: "La Fonda de Cal Fuxet",
          place: "Lles de Cerdanya (Aransa)",
          capacity: "4 habitacions, fins a 12 pax",
          tags: ["Familiar", "Vistes al Cadí", "Cuina de proximitat"],
          tone: "stone",
        },
        {
          name: "Mas d'Aravó",
          place: "Bolvir (Talltorta)",
          capacity: "4 apartaments, fins a 25 pax",
          tags: ["Agroturisme", "Natura", "Grups"],
          tone: "stone",
        },
        {
          name: "Hotel Can Borrell",
          place: "Meranges",
          capacity: "Fins a 20 pax",
          tags: ["Hotel rural", "1.500m altitud", "Gastronomia km0"],
          tone: "alpine",
        },
        {
          name: "Aparthotel Les Corts",
          place: "Llívia",
          capacity: "8 habitacions, fins a 25 pax",
          tags: ["Centre Llívia", "Piscina coberta", "Gimnàs"],
          tone: "stone",
        },
        {
          name: "Hotel Cal Rei de Talló",
          place: "Bellver de Cerdanya",
          capacity: "10 habitacions, fins a 39 pax",
          tags: ["Hotel rural", "Minimalista", "Reunions tranquil·les"],
          tone: "forest",
        },
        {
          name: "Els Isards",
          place: "Alp (la Molina)",
          capacity: "9 habitacions, fins a 49 pax",
          tags: ["Alberg", "Peu de pistes", "Hivern/estiu"],
          tone: "ice",
        },
        {
          name: "Refugi Malniu",
          place: "Meranges",
          capacity: "Fins a 40 pax",
          tags: ["Refugi alt muntanya", "Sala multimèdia", "Estanys naturals"],
          tone: "summit",
        },
        {
          name: "Colmado - Llívia by Albert Boronat",
          place: "Llívia",
          capacity: "Càtering fins a 300 pax",
          tags: ["Gastronomia d'altura", "Team building", "Showcoking"],
          tone: "wine",
        },        {
          name: "Hotel Torre del Remei",
          place: "Bolvir",
          capacity: "24 habitaciones, hasta 55 pax",
          tags: ["Palacete modernista", "Jardines de 3 ha", "Gastronomía de calidad"],
          tone: "wine",
        },
        {
          name: "Hotel del Prado",
          place: "Puigcerdà",
          capacity: "56 habitaciones, hasta 110 pax",
          tags: ["Hotel gastronómico", "Jardín y piscina", "Producto km0"],
          tone: "wine",
        },
        {
          name: "Hotel Fontanals Golf",
          place: "Fontanals de Cerdanya",
          capacity: "60 habitaciones, hasta 180 pax",
          tags: ["Golf", "Esquí", "Senderismo"],
          tone: "forest",
        },
        {
          name: "Hotel&Spa La Collada",
          place: "Toses",
          capacity: "90 habitaciones, hasta 270 pax",
          tags: ["Spa", "Piscina climatizada", "Salas reuniones"],
          tone: "alpine",
        },
        {
          name: "Hotel Villa Paulita",
          place: "Puigcerdà",
          capacity: "35 habitaciones, hasta 80 pax",
          tags: ["Modernista", "Vistas al lago", "Grupos MICE"],
          tone: "stone",
        },
        {
          name: "Hotel Solineu",
          place: "Alp (la Molina)",
          capacity: "53 hab + 35 apart, hasta 137 pax",
          tags: ["Ambiente familiar", "Todo el año", "Salas reuniones"],
          tone: "ice",
        },
        {
          name: "Hotel-Restaurant Ca l'Eudald",
          place: "Alp",
          capacity: "25 habitaciones, hasta 62 pax",
          tags: ["Cocina pirenaica", "Terraza con jardín", "Grupos"],
          tone: "forest",
        },
        {
          name: "La Fonda de Cal Fuxet",
          place: "Lles de Cerdanya (Aransa)",
          capacity: "4 habitaciones, hasta 12 pax",
          tags: ["Familiar", "Vistas al Cadí", "Cocina de proximidad"],
          tone: "stone",
        },
        {
          name: "Aparthotel Les Corts",
          place: "Llívia",
          capacity: "8 habitaciones, hasta 25 pax",
          tags: ["Centro Llívia", "Piscina cubierta", "Gimnasio"],
          tone: "stone",
        },
        {
          name: "Hotel Cal Rei de Talló",
          place: "Bellver de Cerdanya",
          capacity: "10 habitaciones, hasta 39 pax",
          tags: ["Hotel rural", "Minimalista", "Reuniones tranquilas"],
          tone: "forest",
        },
        {
          name: "Colmado - Llívia by Albert Boronat",
          place: "Llívia",
          capacity: "Catering hasta 300 pax",
          tags: ["Gastronomía de altura", "Team building", "Showcoking"],
          tone: "wine",
        },      ],
    },
    team: {
      eyebrow: "Equip",
      title: "Un grup petit, sènior, i resident a la vall.",
      lead:
        "Som vuit persones. Cada projecte té una direcció dedicada que t'acompanya de la primera trucada al darrer factura.",
      members: [
        ["Núria Brangulí", "Direcció general", "Sòcia fundadora. Estratègia, clients i relació institucional."],
        ["Marc Pons", "Direcció de producció", "Soci fundador. Logística, calendari i execució integral."],
        ["Aina Vidal", "Direcció de comunicació", "Sòcia fundadora. Relat editorial, premsa i creators."],
        ["Jordi Tomàs", "DMC & operacions", "Soci fundador. Guia de muntanya UIMLA. Cerdà de tota la vida."],
      ],
    },
    journal: {
      eyebrow: "Diari",
      title: "Notes des de la vall.",
      lead: "Idees, casos i aprenentatges del que produïm.",
      posts: [
        ["Manifest", "Per què neix Alpinea i què volem canviar al sector MICE a la Cerdanya", "6 min"],
        ["Tendències", "MICE 2026: per què les marques marxen de les capitals", "5 min"],
        ["Territori", "12 productors de la Cerdanya que cada esdeveniment hauria de conèixer", "6 min"],
      ],
    },
    contact: {
      eyebrow: "Contacte",
      title: "Expliquem-nos el projecte.",
      lead:
        "Resposta en menys de 24 hores laborables. Pressupost orientatiu en 5 dies. T'acompanyem des de la primera trucada.",
      fields: {
        name: "Nom i cognoms",
        company: "Empresa o organització",
        email: "Correu electrònic",
        phone: "Telèfon",
        type: "Tipus de projecte",
        date: "Dates aproximades",
        guests: "Nombre d'assistents",
        message: "Explica'ns el projecte",
        submit: "Enviar sol·licitud",
      },
      types: ["Convenció corporativa", "Incentiu / team building", "Congrés", "Comunicació / RRPP", "Producció audiovisual", "Boda / privat", "Altres"],
      info: [
        ["Estudi", "Plaça dels Herois, 4\n17520 Puigcerdà"],
        ["Email", "hola@alpinea.cat"],
        ["Telèfon", "+34 972 14 02 88"],
        ["Horari", "Dl–Dv · 9.00–18.30"],
      ],
    },
    footer: {
      manifesto: "Una agència de la Cerdanya, per a marques de tot arreu.",
      legal: ["Avís legal", "Privacitat", "Cookies", "Codi ètic"],
      copy: "© 2026 Alpinea SL · CIF B-09877654 · Inscrita al Registre Mercantil de Girona.",
    },
  },

  es: {
    nav: {
      about: "Estudio",
      services: "Servicios",
      packs: "Packs",
      venues: "Espacios",
      team: "Equipo",
      journal: "Diario",
      contact: "Contacto",
      cta: "Solicitar propuesta",
    },
    hero: {
      eyebrow: "Agencia MICE & Comunicación · Cerdanya",
      title: ["Eventos", "de altura,", "hechos a medida", "del Pirineo."],
      titleClean: "Eventos de altura, hechos a medida del Pirineo.",
      lead:
        "Diseñamos encuentros corporativos, congresos, incentivos y campañas de comunicación que aprovechan la energía, el paisaje y la artesanía de la Cerdanya. Cada proyecto, una experiencia irrepetible a 1.200 metros.",
      ctaPrimary: "Empecemos un proyecto",
      ctaSecondary: "Ver carta de servicios",
      stat1: ["8", "personas en el estudio"],
      stat2: ["38", "espacios singulares seleccionados"],
      stat3: ["1.200 m", "altitud media del valle"],
    },
    about: {
      eyebrow: "Estudio",
      title: "Una agencia arraigada al territorio, pensada para marcas exigentes.",
      body: [
        "Alpinea nace este 2026 en Puigcerdà como la primera agencia especializada de la Cerdanya en MICE, eventos corporativos y comunicación estratégica. Combinamos la mirada editorial de un estudio creativo con el rigor operativo de una DMC.",
        "Queremos trabajar con empresas, instituciones y marcas que buscan un escenario distinto: un entorno natural de alta montaña, una red de proveedores locales de confianza y un equipo que conoce cada valle, cada masía y cada cocinero del territorio.",
      ],
      pillars: [
        ["01", "Conocimiento del territorio", "Hemos caminado, dormido y cocinado en cada espacio que ofrecemos."],
        ["02", "Producción rigurosa", "Presupuestos transparentes, calendario realista, ejecución impecable."],
        ["03", "Mirada editorial", "Cada evento se comunica antes, durante y después como una historia."],
        ["04", "Huella local", "Trabajamos con productores, artesanos y guías del valle."],
      ],
    },
    services: {
      eyebrow: "Carta de servicios",
      title: "Todo lo que necesitas para producir, comunicar y hacer memorable un proyecto.",
      lead:
        "Ofrecemos cobertura 360°: desde la primera idea y la búsqueda de espacio hasta la cobertura de prensa y el material audiovisual final.",
      categories: [
        { tag: "01 — MICE", name: "Eventos corporativos", desc: "Convenciones, kick-offs, juntas y jornadas estratégicas con producción integral y acompañamiento ejecutivo.", items: ["Convenciones y kick-offs", "Juntas y consejos", "Lanzamientos de producto", "Activaciones de marca"] },
        { tag: "02 — Incentivos", name: "Incentivos y team building", desc: "Programas de 2 a 5 días con actividades outdoor, gastronomía de autor y alojamientos singulares.", items: ["Esquí, raquetas y mushing", "Rutas BTT y trekking", "Talleres gastronómicos", "Wellness y montaña"] },
        { tag: "03 — Congresos", name: "Congresos y convenciones", desc: "Secretaría técnica, gestión de inscripciones, ponentes y streaming para eventos de hasta 600 asistentes.", items: ["Secretaría técnica", "Gestión de ponentes", "Streaming e híbridos", "Apps y acreditaciones"] },
        { tag: "04 — DMC", name: "Destination Management", desc: "Somos tu partner local: transfers, alojamientos, restauración, guías y logística de última milla.", items: ["Búsqueda y contratación de espacios", "Transfers y movilidad", "Hospitality desks", "Acompañamiento 24/7"] },
        { tag: "05 — Comunicación", name: "Comunicación & RRPP", desc: "Estrategia, relato y relación con medios antes, durante y después del evento para amplificar el impacto.", items: ["Estrategia y mensajes clave", "Notas y ruedas de prensa", "Influencer & creator relations", "Cobertura editorial"] },
        { tag: "06 — Producción", name: "Producción audiovisual", desc: "Vídeo, fotografía y dirección de arte en localizaciones únicas de la Cerdanya, con equipos locales.", items: ["Vídeo corporativo y aftermovie", "Fotografía editorial", "Dirección de arte", "Streaming multicámara"] },
        { tag: "07 — Branding", name: "Identidad & diseño", desc: "Identidad visual del evento, sistema gráfico, señalética y materiales impresos con cuidado artesanal.", items: ["Naming y clave visual", "Señalética y wayfinding", "Invitados y merchandising", "Webs y landings"] },
        { tag: "08 — Bodas", name: "Bodas & celebraciones privadas", desc: "Un número limitado de celebraciones privadas al año, con la misma exigencia editorial que los proyectos corporativos.", items: ["Dirección creativa", "Producción integral", "Coordinación de proveedores", "Wedding concierge"] },
      ],
    },
    packs: {
      eyebrow: "Packs",
      title: "Productos cerrados, listos para reservar.",
      lead:
        "Cuatro programas ya diseñados que combinan alojamiento, espacio, restauración y actividades. Punto de partida; los personalizamos contigo en una llamada.",
      note: "Precios orientativos por persona, IVA no incluido. Mínimo 20 pax. Disponibilidad según temporada.",
      ctaPack: "Quiero este pack",
      ctaCustom: "Quiero uno a medida",
      labels: { duration: "Duración", group: "Grupo", season: "Temporada", from: "Desde", includes: "Qué incluye" },
      list: [
        { code: "P01", slug: "cims-estrategia", name: "Cumbres & Estrategia", tag: "Off-site ejecutivo",
          tagline: "Dos días para pensar lejos y decidir cerca.",
          duration: "2 días / 1 noche", group: "8–20 pax", season: "Todo el año",
          price: "1.180 €", tone: "alpine",
          includes: [
            ["Alojamiento", "Mas de la Coma · habitación boutique"],
            ["Espacio", "Sala de juntas con vistas + breakout en el bosque"],
            ["Restauración", "Desayuno, comida de trabajo, cena de degustación (5 tiempos)"],
            ["Actividades", "Trekking guiado a la Tossa Plana + sesión wellness"],
            ["Extra", "Facilitador estratégico + acta visual de la jornada"],
          ],
        },
        { code: "P02", slug: "kick-off-cerdanya", name: "Kick-off Cerdanya", tag: "Convención anual",
          tagline: "Todo el equipo, un fin de semana, un valle.",
          duration: "3 días / 2 noches", group: "80–300 pax", season: "Sep–Jun",
          price: "780 €", tone: "crowd",
          includes: [
            ["Alojamiento", "Hotel del Llac ★★★★ · pensión completa"],
            ["Espacio", "Sala plenaria + 4 breakouts + plaza para gala"],
            ["Restauración", "Coffee artesano, comida buffet, cena de gala de autor"],
            ["Actividades", "Team building \"Travesía de la Cerdanya\" + cata de quesos"],
            ["Extra", "Producción audiovisual (aftermovie 90'') + señalética"],
          ],
        },
        { code: "P03", slug: "snow-incentive", name: "Snow Incentive", tag: "Incentivo invierno",
          tagline: "Esquí por la mañana, gala por la noche.",
          duration: "3 días / 2 noches", group: "30–120 pax", season: "Dic–Mar",
          price: "1.450 €", tone: "ice",
          includes: [
            ["Alojamiento", "Hotel boutique a pie de pistas"],
            ["Espacio", "Restaurante de altura privatizado + sala de juntas"],
            ["Restauración", "Desayuno montaña, comida en pistas, cena maridada"],
            ["Actividades", "Esquí con monitor, raquetas, mushing o spa"],
            ["Extra", "Forfaits, transfers y material incluidos"],
          ],
        },
        { code: "P04", slug: "estiu-editorial", name: "Verano Editorial", tag: "Press trip & activación",
          tagline: "Tres días para periodistas, creators y clientes top.",
          duration: "3 días / 2 noches", group: "12–40 pax", season: "Jun–Sep",
          price: "1.290 €", tone: "forest",
          includes: [
            ["Alojamiento", "Masía Cal Marrufès · habitaciones singulares"],
            ["Espacio", "Patio exterior, era y bodega privatizados"],
            ["Restauración", "Tres comidas km0 con chef invitado"],
            ["Actividades", "Ruta gastronómica + taller artesano + baño en el río"],
            ["Extra", "Fotógrafo editorial + kit de prensa personalizado"],
          ],
        },
      ],
    },
    venues: {
      eyebrow: "Espacios",
      title: "Una red de 38 venues seleccionados en el valle.",
      lead: "Trabajamos con alojamientos, restaurantes, espacios singulares y empresas de servicios por toda la Cerdanya. Aquí está nuestra selección completa de partners de calidad.",
      list: [
        { name: "Hotel Bernat de So", place: "Llívia", capacity: "21 habitaciones, hasta 31 pax", tags: ["Hotel ★★★", "Sala reuniones", "Sostenible"], tone: "stone" },
        { name: "Hotel del Lago", place: "Puigcerdà", capacity: "21 habitaciones, hasta 41 pax", tags: ["Hotel ★★★★", "Spa", "Piscina climatizada"], tone: "lake" },
        { name: "Cerdanya Viva", place: "Prullans", capacity: "102 habitaciones, hasta 437 pax", tags: ["Ecohotel", "Sala gran formato", "Turismo regenerativo"], tone: "forest" },
        { name: "Alp Hotel Masella", place: "Alp (Masella)", capacity: "146 habitaciones, hasta 600 pax", tags: ["Hotel ★★★", "A pie de pistas", "Piscina interior/exterior"], tone: "ice" },
        { name: "Hotel Torre del Remei", place: "Bolvir", capacity: "24 habitaciones, hasta 55 pax", tags: ["Palacete modernista", "Jardines de 3 ha", "Gastronomía de calidad"], tone: "wine" },
        { name: "Hotel del Prado", place: "Puigcerdà", capacity: "56 habitaciones, hasta 110 pax", tags: ["Hotel gastronómico", "Jardín y piscina", "Producto km0"], tone: "wine" },
        { name: "Hotel Fontanals Golf", place: "Fontanals de Cerdanya", capacity: "60 habitaciones, hasta 180 pax", tags: ["Golf", "Esquí", "Senderismo"], tone: "forest" },
        { name: "Hotel&Spa La Collada", place: "Toses", capacity: "90 habitaciones, hasta 270 pax", tags: ["Spa", "Piscina climatizada", "Salas reuniones"], tone: "alpine" },
        { name: "Hotel Villa Paulita", place: "Puigcerdà", capacity: "35 habitaciones, hasta 80 pax", tags: ["Modernista", "Vistas al lago", "Grupos MICE"], tone: "stone" },
        { name: "Hotel Solineu", place: "Alp (la Molina)", capacity: "53 hab + 35 apart, hasta 137 pax", tags: ["Ambiente familiar", "Todo el año", "Salas reuniones"], tone: "ice" },
        { name: "Hotel-Restaurant Ca l'Eudald", place: "Alp", capacity: "25 habitaciones, hasta 62 pax", tags: ["Cocina pirenaica", "Terraza con jardín", "Grupos"], tone: "forest" },
        { name: "Cal Rei", place: "Lles de Cerdanya", capacity: "Hasta 25 pax", tags: ["Alojamiento rural", "Restaurante", "Vistas al Cadí-Moixeró"], tone: "alpine" },
        { name: "Les Feixes Llargues", place: "Bolvir", capacity: "Hasta 19 pax", tags: ["Alojamiento rural", "Sala reuniones", "Sostenible"], tone: "forest" },
        { name: "La Fonda de Cal Fuxet", place: "Lles de Cerdanya (Aransa)", capacity: "4 habitaciones, hasta 12 pax", tags: ["Familiar", "Vistas al Cadí", "Cocina de proximidad"], tone: "stone" },
        { name: "Mas d'Aravó", place: "Bolvir (Talltorta)", capacity: "4 apartamentos, hasta 25 pax", tags: ["Agroturismo", "Naturaleza", "Grupos"], tone: "stone" },
        { name: "Hotel Can Borrell", place: "Meranges", capacity: "Hasta 20 pax", tags: ["Hotel rural", "1.500m altitud", "Gastronomía km0"], tone: "alpine" },
        { name: "Aparthotel Les Corts", place: "Llívia", capacity: "8 habitaciones, hasta 25 pax", tags: ["Centro Llívia", "Piscina cubierta", "Gimnasio"], tone: "stone" },
        { name: "Hotel Cal Rei de Talló", place: "Bellver de Cerdanya", capacity: "10 habitaciones, hasta 39 pax", tags: ["Hotel rural", "Minimalista", "Reuniones tranquilas"], tone: "forest" },
        { name: "Els Isards", place: "Alp (la Molina)", capacity: "9 habitaciones, hasta 49 pax", tags: ["Albergue", "A pie de pistas", "Invierno/verano"], tone: "ice" },
        { name: "Refugio Malniu", place: "Meranges", capacity: "Hasta 40 pax", tags: ["Refugio alta montaña", "Sala multimedia", "Lagos naturales"], tone: "summit" },
        { name: "Colmado - Llívia by Albert Boronat", place: "Llívia", capacity: "Catering hasta 300 pax", tags: ["Gastronomía de altura", "Team building", "Showcoking"], tone: "wine" },
      ],
    },
    team: {
      eyebrow: "Equipo",
      title: "Un grupo pequeño, senior y residente en el valle.",
      lead: "Somos ocho personas. Cada proyecto tiene una dirección dedicada que te acompaña desde la primera llamada.",
      members: [
        ["Núria Brangulí", "Dirección general", "Socia fundadora. Estrategia, clientes y relación institucional."],
        ["Marc Pons", "Dirección de producción", "Socio fundador. Logística, calendario y ejecución integral."],
        ["Aina Vidal", "Dirección de comunicación", "Socia fundadora. Relato editorial, prensa y creators."],
        ["Jordi Tomàs", "DMC & operaciones", "Socio fundador. Guía de montaña UIMLA. Cerdano de toda la vida."],
      ],
    },
    journal: {
      eyebrow: "Diario",
      title: "Notas desde el valle.",
      lead: "Ideas, casos y aprendizajes de lo que producimos.",
      posts: [
        ["Manifiesto", "Por qué nace Alpinea y qué queremos cambiar en el MICE de la Cerdanya", "6 min"],
        ["Tendencias", "MICE 2026: por qué las marcas se van de las capitales", "5 min"],
        ["Territorio", "12 productores de la Cerdanya que todo evento debería conocer", "6 min"],
      ],
    },
    contact: {
      eyebrow: "Contacto",
      title: "Cuéntanos el proyecto.",
      lead: "Respuesta en menos de 24 horas laborables. Presupuesto orientativo en 5 días.",
      fields: {
        name: "Nombre y apellidos",
        company: "Empresa u organización",
        email: "Correo electrónico",
        phone: "Teléfono",
        type: "Tipo de proyecto",
        date: "Fechas aproximadas",
        guests: "Número de asistentes",
        message: "Cuéntanos el proyecto",
        submit: "Enviar solicitud",
      },
      types: ["Convención corporativa", "Incentivo / team building", "Congreso", "Comunicación / RRPP", "Producción audiovisual", "Boda / privado", "Otros"],
      info: [
        ["Estudio", "Plaça dels Herois, 4\n17520 Puigcerdà"],
        ["Email", "hola@alpinea.cat"],
        ["Teléfono", "+34 972 14 02 88"],
        ["Horario", "L–V · 9.00–18.30"],
      ],
    },
    footer: {
      manifesto: "Una agencia de la Cerdanya, para marcas de cualquier lugar.",
      legal: ["Aviso legal", "Privacidad", "Cookies", "Código ético"],
      copy: "© 2026 Alpinea SL · CIF B-09877654 · Inscrita en el Registro Mercantil de Girona.",
    },
  },

  en: {
    nav: {
      about: "Studio",
      services: "Services",
      packs: "Packs",
      venues: "Venues",
      team: "Team",
      journal: "Journal",
      contact: "Contact",
      cta: "Request a proposal",
    },
    hero: {
      eyebrow: "MICE & Communications agency · Cerdanya",
      title: ["High-altitude", "events,", "tailor-made", "in the Pyrenees."],
      titleClean: "High-altitude events, tailor-made in the Pyrenees.",
      lead:
        "We design corporate gatherings, congresses, incentives and communication campaigns that draw on the energy, the landscape and the craft of the Cerdanya valley. Every project, an experience that only happens at 1,200 metres.",
      ctaPrimary: "Start a project",
      ctaSecondary: "See our service menu",
      stat1: ["8", "people in the studio"],
      stat2: ["38", "signature venues across the valley"],
      stat3: ["1,200 m", "average altitude of the valley"],
    },
    about: {
      eyebrow: "Studio",
      title: "An agency rooted in its territory, built for demanding brands.",
      body: [
        "Alpinea is born in Puigcerdà in 2026 as the Cerdanya valley's first specialised agency for MICE, corporate events and strategic communications. We combine the editorial eye of a creative studio with the operational rigour of a destination management company.",
        "We want to work with companies, institutions and brands looking for a different stage: a high-mountain natural setting, a trusted network of local suppliers and a team that knows every valley, every farmhouse and every chef in the territory.",
      ],
      pillars: [
        ["01", "Local knowledge", "We've walked, slept and cooked at every venue we offer."],
        ["02", "Rigorous production", "Transparent budgets, realistic timelines, flawless delivery."],
        ["03", "Editorial eye", "Every event is told as a story — before, during and after."],
        ["04", "Local footprint", "We work with producers, artisans and mountain guides from the valley."],
      ],
    },
    services: {
      eyebrow: "Service menu",
      title: "Everything you need to produce, communicate and make a project memorable.",
      lead: "End-to-end coverage: from the first idea and venue scouting through to press coverage and the final film.",
      categories: [
        { tag: "01 — MICE", name: "Corporate events", desc: "Conventions, kick-offs, board meetings and strategy days with end-to-end production and executive support.", items: ["Conventions & kick-offs", "Boards & off-sites", "Product launches", "Brand activations"] },
        { tag: "02 — Incentives", name: "Incentives & team building", desc: "Two- to five-day programmes with outdoor activities, signature gastronomy and standout accommodation.", items: ["Ski, snowshoe & mushing", "MTB & trekking routes", "Gastronomy workshops", "Wellness & mountain"] },
        { tag: "03 — Congresses", name: "Congresses & conventions", desc: "Technical secretariat, registration, speaker management and streaming for events up to 600 attendees.", items: ["Technical secretariat", "Speaker management", "Streaming & hybrid", "Apps & accreditations"] },
        { tag: "04 — DMC", name: "Destination Management", desc: "Your local partner: transfers, accommodation, F&B, guides and last-mile logistics.", items: ["Venue scouting & contracting", "Transfers & mobility", "Hospitality desks", "24/7 support"] },
        { tag: "05 — Communications", name: "Communications & PR", desc: "Strategy, narrative and media relations before, during and after the event to amplify its impact.", items: ["Strategy & key messages", "Press releases & briefings", "Creator & influencer relations", "Editorial coverage"] },
        { tag: "06 — Production", name: "Audiovisual production", desc: "Film, photography and art direction in unique Cerdanya locations, with local crews.", items: ["Corporate film & aftermovie", "Editorial photography", "Art direction", "Multi-camera streaming"] },
        { tag: "07 — Branding", name: "Identity & design", desc: "Event identity, graphic system, signage and printed materials with artisan care.", items: ["Naming & key visual", "Signage & wayfinding", "Guest kits & merch", "Websites & landings"] },
        { tag: "08 — Weddings", name: "Weddings & private celebrations", desc: "A limited number of private celebrations per year, with the same editorial standard as our corporate work.", items: ["Creative direction", "Full production", "Supplier coordination", "Wedding concierge"] },
      ],
    },
    packs: {
      eyebrow: "Packs",
      title: "Ready-made programmes, ready to book.",
      lead:
        "Four pre-designed programmes that combine accommodation, venue, F&B and activities. A starting point — we tailor each one in a single call.",
      note: "Indicative prices per person, VAT not included. Minimum 20 pax. Subject to seasonal availability.",
      ctaPack: "I want this pack",
      ctaCustom: "I want a custom one",
      labels: { duration: "Duration", group: "Group", season: "Season", from: "From", includes: "What's included" },
      list: [
        { code: "P01", slug: "cims-estrategia", name: "Summits & Strategy", tag: "Executive off-site",
          tagline: "Two days to think far and decide close.",
          duration: "2 days / 1 night", group: "8–20 pax", season: "Year-round",
          price: "€1,180", tone: "alpine",
          includes: [
            ["Stay", "Mas de la Coma · boutique room"],
            ["Venue", "Boardroom with views + breakout in the forest"],
            ["F&B", "Breakfast, working lunch, 5-course tasting dinner"],
            ["Activities", "Guided trek to Tossa Plana + wellness session"],
            ["Extra", "Strategic facilitator + visual minutes"],
          ],
        },
        { code: "P02", slug: "kick-off-cerdanya", name: "Kick-off Cerdanya", tag: "Annual convention",
          tagline: "The whole team, one weekend, one valley.",
          duration: "3 days / 2 nights", group: "80–300 pax", season: "Sep–Jun",
          price: "€780", tone: "crowd",
          includes: [
            ["Stay", "Hotel del Llac ★★★★ · full board"],
            ["Venue", "Plenary hall + 4 breakouts + plaza for gala"],
            ["F&B", "Artisan coffee, buffet lunch, signature gala dinner"],
            ["Activities", "\"Cerdanya Traverse\" team-building + cheese tasting"],
            ["Extra", "Aftermovie (90'') + signage system"],
          ],
        },
        { code: "P03", slug: "snow-incentive", name: "Snow Incentive", tag: "Winter incentive",
          tagline: "Skiing by day, gala by night.",
          duration: "3 days / 2 nights", group: "30–120 pax", season: "Dec–Mar",
          price: "€1,450", tone: "ice",
          includes: [
            ["Stay", "Ski-in/ski-out boutique hotel"],
            ["Venue", "Private mountaintop restaurant + boardroom"],
            ["F&B", "Mountain breakfast, slope-side lunch, paired dinner"],
            ["Activities", "Ski lessons, snowshoes, mushing or spa"],
            ["Extra", "Lift passes, transfers and gear included"],
          ],
        },
        { code: "P04", slug: "estiu-editorial", name: "Editorial Summer", tag: "Press trip & activation",
          tagline: "Three days for journalists, creators and top clients.",
          duration: "3 days / 2 nights", group: "12–40 pax", season: "Jun–Sep",
          price: "€1,290", tone: "forest",
          includes: [
            ["Stay", "Cal Marrufès farmhouse · signature rooms"],
            ["Venue", "Private courtyard, threshing floor and winery"],
            ["F&B", "Three km-zero meals with guest chef"],
            ["Activities", "Gastronomy route + artisan workshop + river bath"],
            ["Extra", "Editorial photographer + bespoke press kit"],
          ],
        },
      ],
    },
    venues: {
      eyebrow: "Venues",
      title: "A curated network of 38 venues across the valley.",
      lead: "We work with accommodation, restaurants, signature spaces and service companies throughout the Cerdanya. Here is our complete selection of quality partners.",
      list: [
        { name: "Hotel Bernat de So", place: "Llívia", capacity: "21 rooms, up to 31 pax", tags: ["★★★ hotel", "Meeting hall", "Sustainable"], tone: "stone" },
        { name: "Hotel del Lago", place: "Puigcerdà", capacity: "21 rooms, up to 41 pax", tags: ["★★★★ hotel", "Spa", "Indoor pool"], tone: "lake" },
        { name: "Cerdanya Viva", place: "Prullans", capacity: "102 rooms, up to 437 pax", tags: ["Ecohotel", "Large-format hall", "Regenerative tourism"], tone: "forest" },
        { name: "Alp Hotel Masella", place: "Alp (Masella)", capacity: "146 rooms, up to 600 pax", tags: ["★★★ hotel", "Ski-in/ski-out", "Indoor/outdoor pool"], tone: "ice" },
        { name: "Hotel Torre del Remei", place: "Bolvir", capacity: "24 rooms, up to 55 pax", tags: ["Art Nouveau mansion", "3-hectare gardens", "Quality gastronomy"], tone: "wine" },
        { name: "Hotel del Prado", place: "Puigcerdà", capacity: "56 rooms, up to 110 pax", tags: ["Gastronomic hotel", "Garden and pool", "km-zero products"], tone: "wine" },
        { name: "Hotel Fontanals Golf", place: "Fontanals de Cerdanya", capacity: "60 rooms, up to 180 pax", tags: ["Golf", "Skiing", "Hiking"], tone: "forest" },
        { name: "Hotel&Spa La Collada", place: "Toses", capacity: "90 rooms, up to 270 pax", tags: ["Spa", "Heated pool", "Meeting rooms"], tone: "alpine" },
        { name: "Hotel Villa Paulita", place: "Puigcerdà", capacity: "35 rooms, up to 80 pax", tags: ["Art Nouveau", "Lake views", "MICE groups"], tone: "stone" },
        { name: "Hotel Solineu", place: "Alp (la Molina)", capacity: "53 rooms + 35 apts, up to 137 pax", tags: ["Family atmosphere", "Year-round", "Meeting rooms"], tone: "ice" },
        { name: "Hotel-Restaurant Ca l'Eudald", place: "Alp", capacity: "25 rooms, up to 62 pax", tags: ["Pyrenean cuisine", "Garden terrace", "Groups"], tone: "forest" },
        { name: "Cal Rei", place: "Lles de Cerdanya", capacity: "Up to 25 pax", tags: ["Rural lodging", "Restaurant", "Views of Cadí-Moixeró"], tone: "alpine" },
        { name: "Les Feixes Llargues", place: "Bolvir", capacity: "Up to 19 pax", tags: ["Rural lodging", "Meeting room", "Sustainable"], tone: "forest" },
        { name: "La Fonda de Cal Fuxet", place: "Lles de Cerdanya (Aransa)", capacity: "4 rooms, up to 12 pax", tags: ["Family-run", "Cadí views", "Local cuisine"], tone: "stone" },
        { name: "Mas d'Aravó", place: "Bolvir (Talltorta)", capacity: "4 apartments, up to 25 pax", tags: ["Agritourism", "Nature", "Groups"], tone: "stone" },
        { name: "Hotel Can Borrell", place: "Meranges", capacity: "Up to 20 pax", tags: ["Rural hotel", "1,500m altitude", "km-zero cuisine"], tone: "alpine" },
        { name: "Aparthotel Les Corts", place: "Llívia", capacity: "8 rooms, up to 25 pax", tags: ["Llívia center", "Indoor pool", "Gym"], tone: "stone" },
        { name: "Hotel Cal Rei de Talló", place: "Bellver de Cerdanya", capacity: "10 rooms, up to 39 pax", tags: ["Rural hotel", "Minimalist", "Tranquil meetings"], tone: "forest" },
        { name: "Els Isards", place: "Alp (la Molina)", capacity: "9 rooms, up to 49 pax", tags: ["Hostel", "Ski-in/ski-out", "Winter/summer"], tone: "ice" },
        { name: "Malniu Refuge", place: "Meranges", capacity: "Up to 40 pax", tags: ["High-altitude refuge", "Multimedia hall", "Natural lakes"], tone: "summit" },
        { name: "Colmado - Llívia by Albert Boronat", place: "Llívia", capacity: "Catering up to 300 pax", tags: ["High-altitude gastronomy", "Team building", "Showcoking"], tone: "wine" },
      ],
    },
    team: {
      eyebrow: "Team",
      title: "A small, senior team — and we live here.",
      lead: "We're eight. Every project gets a dedicated lead from the first call to the final invoice.",
      members: [
        ["Núria Brangulí", "Managing director", "Founding partner. Strategy, clients and institutional relations."],
        ["Marc Pons", "Production director", "Founding partner. Logistics, scheduling and end-to-end delivery."],
        ["Aina Vidal", "Communications director", "Founding partner. Editorial narrative, press and creators."],
        ["Jordi Tomàs", "DMC & operations", "Founding partner. UIMLA mountain guide. Born and raised in the valley."],
      ],
    },
    journal: {
      eyebrow: "Journal",
      title: "Notes from the valley.",
      lead: "Ideas, cases and learnings from what we produce.",
      posts: [
        ["Manifesto", "Why Alpinea exists and what we want to change in Cerdanya's MICE scene", "6 min"],
        ["Trends", "MICE 2026: why brands are leaving the capitals", "5 min"],
        ["Territory", "12 Cerdanya producers every event should know about", "6 min"],
      ],
    },
    contact: {
      eyebrow: "Contact",
      title: "Tell us about your project.",
      lead: "We reply within one business day. A first budget estimate within five.",
      fields: {
        name: "Full name",
        company: "Company or organisation",
        email: "Email",
        phone: "Phone",
        type: "Project type",
        date: "Approximate dates",
        guests: "Number of attendees",
        message: "Tell us about the project",
        submit: "Send request",
      },
      types: ["Corporate convention", "Incentive / team building", "Congress", "Communications / PR", "Audiovisual production", "Wedding / private", "Other"],
      info: [
        ["Studio", "Plaça dels Herois, 4\n17520 Puigcerdà"],
        ["Email", "hola@alpinea.cat"],
        ["Phone", "+34 972 14 02 88"],
        ["Hours", "Mon–Fri · 9.00–18.30"],
      ],
    },
    footer: {
      manifesto: "An agency from the Cerdanya valley, for brands from anywhere.",
      legal: ["Legal notice", "Privacy", "Cookies", "Ethical code"],
      copy: "© 2026 Alpinea SL · CIF B-09877654 · Registered at the Mercantile Register of Girona.",
    },
  },
};
